version: '3.8'

services:
  api:
    container_name: globalonlinebank_api
    build:
      context: .
      dockerfile: ./GlobalOnlinebank.WebApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=GlobalOnlineBankDb;Username=admin;Password=admin123"
    networks:
      - globalonlinebank-net

  postgres:
    image: postgres:16
    container_name: globalonlinebank_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: GlobalOnlineBankDb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - globalonlinebank-net

networks:
  globalonlinebank-net:

volumes:
  pg_data: